# permissions for end users to edit scripts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: script-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: script-operator
    app.kubernetes.io/part-of: script-operator
    app.kubernetes.io/managed-by: kustomize
  name: script-editor-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - scripts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - scripts/status
  verbs:
  - get
